USE chinook;
-- 1. MARKET ANALYSIS: Total Revenue Generated by Each Country

/*
SELECT BillingCountry, ROUND(SUM(Total), 2) AS TotalRevenue
FROM Invoice
group by BillingCountry
ORDER BY TotalRevenue DESC; 

*/
-- 2. PRODUCT MANAGEMENT: Top-Selling Music Genres (Units Sold)

/*SELECT g.Name AS GenreName, COUNT(il.InvoiceLineId) AS TracksSold
FROM InvoiceLine il
JOIN Track t ON il.TrackId = t.TrackId
JOIN Genre g ON t.GenreId = g.GenreId
GROUP BY g.Name
ORDER BY TracksSold DESC;
*/

-- 3. CUSTOMER SEGMENTATION: Identify the Top Spender in Every Country (Using CTE)
/*
WITH Customer_Spending AS (
    SELECT c.FirstName, c.LastName, c.Country, ROUND(SUM(i.Total), 2) AS TotalSpent,
           ROW_NUMBER() OVER(PARTITION BY c.Country ORDER BY SUM(i.Total) DESC) AS Ranking
    FROM Invoice i
    JOIN Customer c ON i.CustomerId = c.CustomerId
    GROUP BY c.CustomerId, c.FirstName, c.LastName, c.Country
)
SELECT FirstName, LastName, Country, TotalSpent
FROM Customer_Spending
WHERE Ranking = 1
ORDER BY TotalSpent DESC;
*/

-- 4. INVENTORY OPTIMIZATION: Identify Unsold Tracks (Subquery & Left Join)

/*
SELECT t.TrackId, t.Name AS TrackName, t.Composer
FROM Track t
LEFT JOIN InvoiceLine il ON t.TrackId = il.TrackId
WHERE il.InvoiceLineId IS NULL
ORDER BY t.Name;

*/

-- 5. TEMPORAL TRENDS: Monthly Sales Volume Analysis (Date Functions)
/*
SELECT MONTHNAME(InvoiceDate) AS MonthName, 
       COUNT(InvoiceId) AS TotalOrders, 
       ROUND(SUM(Total), 2) AS MonthlyRevenue
FROM Invoice
GROUP BY MONTH(InvoiceDate), MONTHNAME(InvoiceDate)
ORDER BY MonthlyRevenue DESC;


*/
